/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TalentirNFT } from "./TalentirNFT";
export * as factories from "./factories";
export { TalentirNFT__factory } from "./factories/TalentirNFT__factory";
