/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Talentir } from "./Talentir";

export { Talentir__factory } from "./factories/Talentir__factory";
